### ISSUE TITLE
Video Speed Controller no longer works in Chrome 80.0.3987.132

### ISSUE THREAD

**Issue by HenryB96** [igrigorik/videospeed#608]
Updated Chrome this morning, and the VSC UI now doesn't appear in any videos. I've tried on Reddit, YouTube, and Facebook, and all of which yield the same console error:
`inject.js:110 Uncaught TypeError: wrapper.createShadowRoot is not a function
at tc.videoController.initializeControls (inject.js:110) 
at new tc.videoController (inject.js:61)
at inject.js:276
at HTMLCollection.forEach (<anonymous>)
at initializeNow (inject.js:275)
at inject.js:177`

**Comment by ChadBailey** [comment]
I updated chrome to check this out and it's working fine on this machine *shrugs*

I'll see if I can check some others, but this may be a local issue

![image](https://user-images.githubusercontent.com/15102816/76145866-6b7b0d80-6053-11ea-8339-182e7b07327d.png)

**Comment by jedawson** [comment]
this was fixed already: https://github.com/igrigorik/videospeed/pull/386
you need to update your extensions.
go to chrome://extensions/ and click developer mode and click update

**Comment by HenryB96** [comment]
Ah yes you're right, updated and now it works. Thanks!
